### PR TITLE
Update kube-prometheus

### PR DESCRIPTION
**Pull request by dud225**
The lokki Grafana datasource is being cleaned out as it isn't used
anywhere.

### CODE REVIEW

**Comment by balchua** [comment]
The loki ds was added to facilitate enabling loki easily for some users.
I'm not sure deleting the loki ds is ok.

**Comment by dud225** [comment]
OK I've put Loki back. 
However I think this is debatable as there is nothing that prevents those users to tweak the data sources on their own. Additionally I don't get the rationale of favouring this particular tool, it's not included in the microk8s addons so why picking this one and not another one?
As far as I'm concerned this extra data source clutters Grafana as there is no working service behind.

**Comment by balchua** [comment]
Thanks @dud225 for this work.  Lgtm 👍

**Comment by berkayoz** [comment]
Hey @dud225 

Thank you for this PR and for your interest. 
We have recently deprecated the `prometheus` plugin and replaced it with the `observability` plugin(#56) that utilizes `kube-prom-stack` helm chart. Could you kindly migrate your changes there if necessary? Thanks.

**Pull request closed without merging**
