### PR TITLE
Reclaim policy for microk8s-hostpath set to Retain

### PR DESCRIPTION
**Pull request by jkosik**
Updating reclaimPolicy for microk8s-hostpath Storage Class from Delete to Retain.

#Fixes https://github.com/canonical/microk8s-community-addons/issues/11 (seems as issue created in a wrong repo)

❯ kubectl get pvc
NAME                    STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS        AGE
pvc-microk8s-hostpath   Bound    pvc-b30f6bd8-08e4-4ea9-9b5f-9c0defa811ca   100Mi      RWO            microk8s-hostpath   22s

❯ kubectl get pv 
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS   CLAIM                           STORAGECLASS        REASON   AGE
pvc-b30f6bd8-08e4-4ea9-9b5f-9c0defa811ca   100Mi      RWO            Retain           Bound    default/pvc-microk8s-hostpath   microk8s-hostpath            9s

❯ kubectl exec busybox-6497c7699d-m2l58 -ti -- sh
/ # touch /mount1/abc
/ # ls /mount1/abc
/mount1/abc
/ # exit

❯ kubectl get po                                 
NAME                       READY   STATUS        RESTARTS   AGE
kube-bench-2z728           0/1     Completed     0          3d12h
busybox-6497c7699d-m2l58   1/1     Terminating   0          88s

❯ kubectl get po
NAME               READY   STATUS      RESTARTS   AGE
kube-bench-2z728   0/1     Completed   0          3d12h
~                                                                                                                                                                 ⎈ microk8s-systemd 08:19:17
❯ kubectl get pvc
No resources found in default namespace.
~                                                                                                                                                                 ⎈ microk8s-systemd 08:19:19
❯ kubectl get pv 
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS     CLAIM                           STORAGECLASS        REASON   AGE
pvc-b30f6bd8-08e4-4ea9-9b5f-9c0defa811ca   100Mi      RWO            Retain           Released   default/pvc-microk8s-hostpath   microk8s-hostpath            2m8s

❯ kubectl describe sc microk8s-hostpath
Name:            microk8s-hostpath
IsDefaultClass:  Yes
Annotations:     kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"storage.k8s.io/v1","kind":"StorageClass","metadata":{"annotations":{"storageclass.kubernetes.io/is-default-class":"true"},"name":"microk8s-hostpath"},"provisioner":"microk8s.io/hostpath","reclaimPolicy":"Retain","volumeBindingMode":"WaitForFirstConsumer"}
,storageclass.kubernetes.io/is-default-class=true
Provisioner:           microk8s.io/hostpath
Parameters:            <none>
AllowVolumeExpansion:  <unset>
MountOptions:          <none>
**ReclaimPolicy:         Retain**
VolumeBindingMode:     WaitForFirstConsumer
Events:                <none>

### CODE REVIEW

**Comment by ktsakalozos** [comment]
Thank you for this PR @jkosik. However, I feel that we would be leaking storage with the reclaim policy set to retain. Right?

**Comment by jkosik** [comment]
@ktsakalozos,  PR is implementation of Reclaim Policy defined in the open [Issue 11](https://github.com/canonical/microk8s-community-addons/issues/11)

**Comment by ktsakalozos** [comment]
I think the right path forward for this is to have the reclaim policy configurable during the `microk8s enable` step.

**Comment by jkosik** [comment]
@ktsakalozos good point, please check update.

**Comment by ktsakalozos** [comment]
This looks much better. Could you please use `--foo` type of arguments to the addon? See [1] as an example.

[1] https://github.com/canonical/microk8s/blob/master/microk8s-resources/wrappers/microk8s-config.wrapper#L16

**Comment by ktsakalozos** [comment]
Thank you for this PR @jkosik.

Your work has been included in https://github.com/canonical/microk8s-core-addons/pull/77

**Pull request closed without merging**
